### ISSUE TITLE
ian-db clustering

### ISSUE THREAD

**Issue by CBenni** [styler/ian-db#2]
Hello, I am a scaling expert for a large company. I need to scale out my fidget spinner distribution system, but I cannot find the auto scaling, sharding and replication features for my 69 OMEGABYTE ian-db cluster.

Any ideas?

**Comment by fourtf** [comment]
Sharding and replication requires a boneless database and has ian-db has bones in it.

**Comment by nuuls** [comment]
🅱⭕🇳🇪🇱🇪🇸🇸

**Comment by CBenni** [comment]
Thank you for your response. I found this plugin on bing: ian-db-boneless.php, which apparently removes the bones from ian-db completely.
It also has a nice printer feature, that allows me to scan the documents I fax from my production server over to the caching server automatically and load them into ian-db as XML.
This puts up a new problem tho: how do I convert XML to HDMI?

**Comment by styler** [comment]
🌚

**Comment by CBenni** [comment]
Any updates on this matter?

**Comment by styler** [comment]
Not yet. 🌚

**Comment by leon-richardt** [comment]
Not yet. 🌚

**Comment by ygolde** [comment]
Are we there yet?

**Comment by 5E7EN** [comment]
FYI, IanDB has started officially supporting clustering since #125. Please be sure to update your clients!
