### ISSUE TITLE
Is Ian-db phpscale?

### ISSUE THREAD

**Issue by gempir** [styler/ian-db#30]
Hello,

I'm writing a high performance web application in php. I need my database to be just as fast as php. Can Ian-db handle this?

**Comment by styler** [comment]
@CBenni Is leading the PHP front of the project. He might be able to provide proper answers here 😎

**Comment by gempir** [comment]
@CBenni ![](https://cdn.frankerfacez.com/4576315ba5c19135139c0782df00770b.png)

**Comment by CBenni** [comment]
@Ian321 helped me with the high performance scaling aspects of ian-db, so it should handle about 1337 memes per 420 seconds and is therefore 69 times faster than PHP itself.

Try vertically scaling your server for even worse performance - this can truly bottleneck your application in a way that guarantees ian-db will never be hacked. It has patented security algorithms written by @ygolde and myself after all.

**Comment by ygolde** [comment]
Indeed. I think this is the first place that we ever implemented our patent pending 
`--iknowthepassword=true` mechanism.
I'm not exactly sure what do you mean by scale, PHP, DB, or security.

**Comment by apa420** [comment]
This issue is out of scope of the Chatterino project.

**Comment by gempir** [comment]
![image](https://user-images.githubusercontent.com/9765622/94949874-f5a02d00-04e1-11eb-82e5-14b333bedadf.png)

**Comment by Ian321** [comment]
![forsenC](https://user-images.githubusercontent.com/14338265/94951603-e1116400-04e4-11eb-8a3b-6f0ac7f19443.png)
