### ISSUE TITLE
Does ian-db utilize blockchain?

### ISSUE THREAD

**Issue by matijakevic** [styler/ian-db#31]
Hey, I am the leading project manager at LordborneTechnologies (R). We are planning to migrate our project to a more modern, safe, agile, fast and fearless technology stack. Because our project depends a lot on blockchain technologies, it's really important that we find a database that utilizes blockchain and is fully compatible with it.

Does ian-db provide such luxury?

**Comment by CBenni** [comment]
Ian-db-boneless (using the boneless-iandb.php plugin) does not have bones in it, so it should be fully compatible with any blockchain stack using md5 for secure encryption. If you need a native integration without the boneless mod, then you could use 2-litre-machine-encryption before that went defunct, not sure if a suitable alternative exists (you could attempt using 1 litre tho)
