### ISSUE TITLE
visual basic condition 

### ISSUE THREAD

**Issue by amine1107** [styler/ian-db#9]
hi
I want to create a variable that carries a text, and render it on a condition
for example
i have a variable "theUser"
and : 

if txtInput.Text contains ("my name is theUser") then 
    text2Input.appendText ("hello theUser")

**Comment by aidenwallis** [comment]
Bump ^

**Comment by aidenwallis** [comment]
bump^

**Comment by aidenwallis** [comment]
bump^

**Comment by aidenwallis** [comment]
bump^

**Comment by aidenwallis** [comment]
bump^

**Comment by aidenwallis** [comment]
bump^

**Comment by sbdonslaught** [comment]
Creating something like this would be quite trivial, and would take way too much time from other projects. For now, this will be closed and may be revisited when we have the resources.
