### ISSUE TITLE
Fearless concurrency???

### ISSUE THREAD

**Issue by RAnders00** [styler/ian-db#90]
rewrite in rust pls

**Comment by styler** [comment]
@CBenni Thoughts?

**Comment by CBenni** [comment]
Rust is a language empowering everyone to build reliable and efficient software.

Why Rust?
Performance
Rust is blazingly fast and memory-efficient: with no runtime or garbage collector, it can power performance-critical services, run on embedded devices, and easily integrate with other languages.

Reliability
Rust’s rich type system and ownership model guarantee memory-safety and thread-safety — enabling you to eliminate many classes of bugs at compile-time.

Productivity
Rust has great documentation, a friendly compiler with useful error messages, and top-notch tooling — an integrated package manager and build tool, smart multi-editor support with auto-completion and type inspections, an auto-formatter, and more.

**Comment by apa420** [comment]
This issue is out of scope of the Chatterino project.
